baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Bottled Pulp'
author = 'BottledPulp'


theme = "hugo-theme-stack"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100

  [menu.main.params]
  icon = "home"
  newTab = false

[[menu.main]]
identifier = "About"
name = "About"
url = "/page/about"
weight = -100

  [menu.main.params]
  icon = "tag"
  newTab = false

[[menu.main]]
identifier = "Search"
name = "Search"
url = "/page/search"
weight = -100

  [menu.main.params]
  icon = "search"
  newTab = false

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/bottled-pulp"

  [menu.social.params]
  icon = "brand-github"

[[menu.social]]
identifier = "instgram"
name = "Instagram"
url = "https://instagram.com/bottled.pulp"

  [menu.social.params]
  icon = "brand-instagram"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200
